#inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

# On an 11-inch screen this works perfectly fine.
Metrics/LineLength:
  Max: 130

# The trailing comma prevents brain cells from dying on copy-paste errors
Style/TrailingCommaInLiteral:
  Enabled: false

# Top-level class documentation is nice, but it's too early in the project to activate this
Style/Documentation:
  Enabled: false
