name: Test Suite
on: [push, pull_request]

jobs:
  check-bats-version:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: bin/build
      - run: bin/test
