name: Test Suite
on: [push, pull_request]

jobs:
  tests:

    strategy:
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - run: bin/build
      - run: bin/test
